#baseURL = 'http://netguardian.io/'
baseURL = 'https://cyberatz.github.io/'
languageCode = 'en-us'
title = 'My Site'
#theme = "ananke"
#theme = "PaperMod"
theme = "paper"

[params]
  disableHLJS = true                         # don't use highlight.js
  #twitter = 'YOUR_TWITTER_ID'                # twitter.com/YOUR_TWITTER_ID
  github = 'cyberatz'
